server:
  port: ${GATEWAY_SERVER_PORT:8080}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
          routes:
            - id: resource-service
              uri: lb://resource-service
              predicates:
                - Path=/resource-service/**
              filters:
                - StripPrefix=1
            - id: song-service
              uri: lb://song-service
              predicates:
                - Path=/song-service/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:discovery-service}:${EUREKA_SERVER_PORT:8761}/eureka
