server:
  port: ${RESOURCE_SERVER_PORT:8081}

spring:
  application:
    name: resource-service
  datasource:
    url: ${RESOURCE_POSTGRES_CONNECTION_STRING:jdbc:postgresql://localhost:5432/resource}
    username: ${RESOURCE_POSTGRES_USER_NAME:resource_user}
    password: ${RESOURCE_POSTGRES_USER_PASSWORD:resource_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ULR:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

rest:
  song_endpoint: ${SONG_SERVICE_URL:http://localhost:8080/song-service/}
