spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://localhost:5432/resource
    username: resource_user
    password: resource_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${RESOURCE_SERVER_PORT:8080}

