spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_RESOURCE_HOST:localhost}:${POSTGRES_RESOURCE_PORT:5432}/${POSTGRES_RESOURCE_DB:resource}
    username: ${POSTGRES_RESOURCE_USER:resource_user}
    password: ${POSTGRES_RESOURCE_PASSWORD:resource_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${RESOURCE_SERVER_PORT:8080}

rest:
  song_endpoint: http://${SONG_SERVER_HOST:localhost}:${SONG_SERVER_POST:8081}/songs
