server:
  port: ${RESOURCE_SERVER_PORT:8081}

spring:
  application:
    name: resource-service
  datasource:
    url: ${RESOURCE_POSTGRES_CONNECTION_STRING:jdbc:postgresql://localhost:5432/resource}
#    url: jdbc:postgresql://${RESOURCE_POSTGRES_HOST:localhost}:${RESOURCE_POSTGRES_PORT:5432}/${RESOURCE_POSTGRES_DB:resource}
    username: ${RESOURCE_POSTGRES_USER_NAME:resource_user}
    password: ${RESOURCE_POSTGRES_USER_PASSWORD:resource_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ULR:http://discovery-service:8761/eureka}

rest:
  song_endpoint: ${SONG_SERVICE_URL:http://localhost:8082}
